spring.application.name=GlobalLocationsInfo

# Custom path for the interactive Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Custom path for the raw JSON OpenAPI definitions
springdoc.api-docs.path=/api-docs
